### ISSUE TITLE
Bad metadata published for org.eclipse.core.contenttype

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.releng#123]
Maven complains that org.eclipse.core.contenttype cannot satisfy its version range

> No versions are present in the repository for the artifact with a range [3.2.0,4.0.0)

I think the problem is that the lowest available version is [3.6.1](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.preferences/3.6.1) here:

https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.preferences

**Comment by merks** [comment]
Are you saying that 3.6.1 does not fall within the range of [3.2.0,4.0.0]?  It seems to me that all the available versions fall within that range:

https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.preferences/

That range is what's specified by in the MANIFEST.MF and certainly OSGi does not consider that wrong:

![image](https://user-images.githubusercontent.com/208716/195389740-7839f983-a021-4a26-92b7-1eb965a43b6e.png)

The analysis view considers it to be correct as well:

![image](https://user-images.githubusercontent.com/208716/195390440-e2d05951-508f-4563-a55a-045db6ad0a46.png)

I even uses org.apache.maven.artifact.versioning.VersionRange.matchVersion(List<ArtifactVersion>) to find the matching version among the available versions.

It's been this way for a very long time, even in this oldest version:

https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.core.contenttype/3.5.100/org.eclipse.core.contenttype-3.5.100.pom

That's because the version range in the MANIFEST.MF is the one you should expect to see in the Maven artifacts.  If you want to see a different range, you'll have to change it in the MANIFEST.MF. 

But why is it suddenly a problem now?  Is it a problem just for this artifact?  And just for this dependency? There's no 3.2.0 version for this either:

https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.registry/

**Comment by merks** [comment]
@laeubi 

Even for EMF I noticed that it publishes artifacts like this:

![image](https://user-images.githubusercontent.com/208716/195779242-039c8bf6-409d-40ec-82c4-7f556916033c.png)

https://repo1.maven.org/maven2/org/eclipse/emf/org.eclipse.emf.ecore/2.28.0/org.eclipse.emf.ecore-2.28.0.pom

Yet there is no 3.6.0 version published:

https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.core.runtime/

Despite that, Xtext has been using EMF's Maven artifacts for many years...

So I think it would be good to understand the following:

- What exactly does "Maven complains" mean? 
- Why can't Maven resolve to an existing artifact within a declared version?
- How exactly how you define "bad metadata"?

**Comment by laeubi** [comment]
@merks it seems a bit related how you reference the artifacts, but I have not found out how to reproduce this reliable. I think it is best to close this until I find a small reproducing test-case.
