### ISSUE TITLE
[PublishToMaven] Replace baseline file by checking the target Maven repository

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.releng#126]
At the moment, the decision whether to push a new version of one artifact or not is made via a `baseline.txt` file which is shared across multiple jobs on CI. This is rather fragile and we should probably target something more robust and simpler.
I suspect `mvn deploy` actually has it built-in: if we try to push an artifact that already exists with the same content in target repo, it may just skip is case file is not changed; or Nexus will fail in case a release was already made with the same version. In such case, we may remove this explicit checks for baseline and rely on Maven to work well.
If Maven isn't smart enough,then we should replace the baseline by retrieving repo metadata and checking whether artifact already existis for the same GAV+checksum. If yes, skip; if not; deploy.

**Comment by merks** [comment]
Note that for publishing EMF to Nexus I do have to check whether that version has already been published and must exclude it. 

I do that in the POMEnhancer:

https://git.eclipse.org/c/emf/org.eclipse.emf.git/tree/releng/org.eclipse.emf.releng/publish/pommod/src/main/java/pommod/POMEnhancer.java

Specifically the POMEnhancer.exists(String, String, String) queries nexus to determine if the artifact with that version is already available and saves a marker file.   Probably there's a better way, but I thought I'd mention it in case that's useful or helpful...

**Comment by mickaelistria** [comment]
Thanks, that's very helpful. I was hoping that Maven/Nexus could deal with this case; but we may still need checks just like you have here.

**Comment by laeubi** [comment]
I just wanted to note that it is not "maven" or "nexus" being not "smart" enough but how maven-deploy plugin currently works, but that don't mean one can't think of an own deploy plugin that works differently... for example there is a nexus-maven-plugin.

https://github.com/sonatype/nexus-maven-plugins/blob/main/staging/maven-plugin/README.md

that has special support for nexus. 

One could even think about a deploy plugin that first checks the maven (remote) repository for existence of an artifact.

**Comment by merks** [comment]
Currently the "Maven" builds fail:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/

That's because the baseline.txt uses - instead of _ in a few places:

![image](https://user-images.githubusercontent.com/208716/207257040-a12e2bfa-24f7-4607-9df1-4885cc6dfab3.png)

Another problem is that this build is supposed to be producing snapshot versions right now,  but it's loading from

https://download.eclipse.org/eclipse/updates/4.26/R-4.26-202211231800

so that's completely useless.

I'll look at fixing these two problem shortly, though I wonder,  are the published snapshots actually used by anything? I would have expected them to be useful for Tycho...

I wonder too, when publishing snapshots we should probably be ignoring the baseline check (or whatever we replace it with), shouldn't we?  Certainly the check ought to be different because we publish the snapshots to repo.eclipse.org not Maven central.

**Comment by merks** [comment]
Oh yes, and I hope we can remove all the hacks around ecj.  I'll investigate that as well.

**Comment by mickaelistria** [comment]
> I wonder too, when publishing snapshots we should probably be ignoring the baseline check (or whatever we replace it with), shouldn't we?

I think it's indeed OK to skip baseline check for snapshots.

**Comment by merks** [comment]
The build is working again:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/

@mickaelistria 

I was thinking of doing the "already published" testing in the aggregator rather than writing more ugly shell script to do that.  One approach would be to create a marker file in the same folder where the artifact's jar/pom are generated.  Or maybe you have other thoughts on how to do this?

**Comment by mickaelistria** [comment]
If the file is a transient one and doesn't need to be maintained/generated, it sounds good.
I imagine the file could be generated with some `curl -H https://repo1.maven.org/maven2/${filePath} && touch ${filePath}.alreadyExistsInCentral"

**Comment by merks** [comment]
@mickaelistria 

FYI, I am working on reducing the three publish(JDT|PDE|Platform).sh scripts, which are near copies of each other, to a single script reused across the three publish jobs. To speed up testing, I created a test job into which I've copied the script:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/PublishTestToMaven/configure

All the mvn calls in the script that do actual work I changed to just "echo" so that the job doesn't really publish anything.

A key change of course is to detect already-published things (which isn't actually relevant for SNAPSHOTs, but needs to be tested:

![image](https://user-images.githubusercontent.com/208716/207387746-31ee1cc5-e847-47c3-80c5-b4bab57057f3.png)

So in the log, we do see sometimes that message is printed:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/PublishTestToMaven/lastBuild/console

> The released version of file org/eclipse/jdt/org.eclipse.jdt.annotation/1.2.100-SNAPSHOT/org.eclipse.jdt.annotation-1.2.100-20220826.102600-0.pom is already present at https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.annotation/1.2.100 but we publish a snapshot version anyway.

I hope to complete these changes and to eliminate all the special handling for ecj tomorrow...

**Comment by mickaelistria** [comment]
@merks all that sounds great! Thanks for taking care of this.

**Comment by merks** [comment]
So the build did fail with this expected failure message in the sources-upload.txt

> BUILD FAILURE org/eclipse/platform/org.eclipse.e4.ui.progress/0.3.700-SNAPSHOT/org.eclipse.e4.ui.progress-0.3.700-20221209.144400-0.jar contains .class files and requires a org/eclipse/platform/org.eclipse.e4.ui.progress/0.3.700-SNAPSHOT/org.eclipse.e4.ui.progress-0.3.700-20221209.144400-0-sources.jar

We'll need a new I-build that fixes issue.

**Comment by merks** [comment]
The most recent build is green.   I added myself to be notified when any of the publishing-related jobs fail in the future.

In the current state, we should detect when published poms fail to resolve and we should detect when source jars are missing for jars that require a source jar (which should generally only happen when a new plugin is introduced).

**Comment by akurtakov** [comment]
It might be best to notify platform-releng-dev on failure too.
