### ISSUE TITLE
Publish Eclipse features to Maven Central

### ISSUE THREAD

**Issue by pzi-dsa** [eclipse-platform/eclipse.platform.releng#27]
Hello everyone,

currently only the Eclipse plugin are published to Maven Central. I think it would be helpful to publish the features, as well.

Use Case:

In order to be FOSS compliant, we want to use Black Duck in combination with Tycho for our RCP application. However, the tool is only able to look at the project from a Maven perspective, meaning that it requires the artifacts to have proper Maven metadata, in order to be detected.

We currently retrieve the Eclipse artifacts via the corresponding p2 repositories and therefore, the tool simply ignores them. So I'm playing with the idea to instead, add them via Maven instead. Which requires a Maven counterpart for both plugins and features.

Is there a technical reason why features can't be published or wasn't there just any need for it so far?

**Comment by vogella** [comment]
@sravanlakkimsetti @akurtakov  WDYT?

**Comment by laeubi** [comment]
> Is there a technical reason why features can't be published

Features can be published as any other artifact, they are not "special" in any regard, its only that until recently there was not much use of a feature to be deployed to maven central. Now we have better maven support in tycho+m2e this might change.
There is still some kind of "gap" e.g. if I add a feature to a pom, what is expected? Should al declared dependencies be included? Or transitive as well? Should that be static (e.g. only published dependencies from the maven model) or dynamic?

But I think all these could better be addresse dif we have some features actually published so one could play around with such artifacts.

That said, there is not really a need to have features at all, as tycho/m2e allows to generate features from maven pom, so one could also simply create a 'pom-feature' that reference regular maven dependencies, that would be more "maven-like" as it will also work for a traditional maven project.

**Comment by akurtakov** [comment]
I don't see a reason to not publish features. The process is too cumbersome for my taste though so we either need help on this one or it will be only after we can deploy in the common maven way.

**Comment by jmini** [comment]
_I am not sure if this is relevant or not of this discussion_

On this topic, please note that in a given P2 Update site, you can have a bundle and a feature sharing the same id.
Example extracted from the 4.14.0 Update Site XML:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<?artifactRepository version='1.1.0'?>
<repository name='Eclipse Project Repository for 2019-12' type='org.eclipse.equinox.p2.artifact.repository.simpleRepository' version='1.0.0'>
<!-- ... -->
  <artifacts size='1326'>
    <artifact classifier='osgi.bundle' id='org.eclipse.rcp' version='4.14.0.v20191210-0610'>
      <!-- ... -->
    </artifact>
    <!-- ... -->
    <artifact classifier='org.eclipse.update.feature' id='org.eclipse.rcp' version='4.14.0.v20191210-0610'>
      <!-- ... -->
    </artifact>
<!-- ... -->
```

So this would mean, invent some mapping between the ID and the GAV so that there is no collision.

**Comment by jmini** [comment]
> In order to be FOSS compliant, we want to use Black Duck in combination with Tycho for our RCP application.

When you look at the content of a feature jar (just some metadata files wrapped into a jar) I am wondering how the feature jars can be relevant for the scanning.

**Comment by jmini** [comment]
Well the `classifier` in a P2 Update site has nothing to do with the `classifier` in maven coordinates.

**Comment by merks** [comment]
Note that p2 appends .feature.group and .feature.jar when representing it as installable units:

![image](https://user-images.githubusercontent.com/208716/174012792-eb8da335-9809-451c-93bb-e7397e9c9f54.png)

**Comment by akurtakov** [comment]
"mapping" in the way it's done now is a no-go considering yesterday fiasco. Using p2 IUs sounds best to me . This might require change/fix in Tycho and/or project(s) poms to adjust artifactIds. 
IMHO this work could be done only after the process is streamlined for bundles and support for uploading snapshots to repo.eclipse.org is there. I think it is totally unacceptable releasing such a thing before more extensive testing e.g. when feature is added as a dependency all required/included plugins are downloaded and available in maven.
This would require some substantial help in order to be done in decent time frame.

**Comment by laeubi** [comment]
> Well the `classifier` in a P2 Update site has nothing to do with the `classifier` in maven coordinates.

It all a matter of definition from maven POV it would be perfectly fine, but if one really wants to publish features to maven one most probably would choose distinct IDs for features/bundles, it is not even required that the GAV(C) has anything to do with the P2 IU ID... so this discussion is quite academic here.

> This might require change/fix in Tycho and/or project(s) poms to adjust artifactIds.

Not really as already as of today each (maven) project has a unique group/artifact id.

**Comment by merks** [comment]
@pzi-dsa  Have you looked at what's in a feature jar?

![image](https://user-images.githubusercontent.com/208716/189862883-14dcc1e0-154c-48ef-baa7-1af3d8972d43.png)

It seems to me that there is literally nothing of interest.  We'd have to provide Javadoc for such a artifact to upload to Nexus, but that would be empty because there are no Java files so such an empty thing might not pass the Nexus tests.  

I don't really see published features actually being significantly useful for anyone such that it would justify the significant additional effort involved in publishing these things.

Note that the CBI aggregator https://github.com/eclipse-cbi/p2repo-aggregator/ can be used to convert a p2 repository to a layout that is also a Maven repository;

![image](https://user-images.githubusercontent.com/208716/189864554-40cf1fca-38de-4f99-abaa-44b49bc73837.png)

It's used by the platform for publishing to Maven...

**Comment by laeubi** [comment]
> It seems to me that there is literally nothing of interest.

Then we really should delete these useless feature files ;-)

> We'd have to provide Javadoc for such a artifact to upload to Nexus, but that would be empty because there are no Java files so such an empty thing might not pass the Nexus tests

Maybe this helps https://stackoverflow.com/questions/53706943/how-to-upload-an-artifact-to-maven-central-with-an-empty-javadoc-jar-or-empty-s

This seems even recommended by https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources

> if, for some reason (for example, license issue or it's a Scala project), you can not provide -sources.jar or -javadoc.jar , please make fake -sources.jar or -javadoc.jar with simple README inside to pass the checking.

> I don't really see published features actually being significantly useful for anyone such that it would justify the significant additional effort involved in publishing these things.

You can consume features in maven targets, and **if a feature would correctly declare its dependencies in the pom** will pull in everything needed here without requiring a P2 repository at all.

**Comment by mickaelistria** [comment]
@pzi-dsa Would you be willing to participate to the development effort? AFAIK, there is currently no other solid use-case in the community that needs this, so I don't imagine this can become high priority of anyone else at the moment.

Technically
I agree this can most likely work if we publish features with the `.feature.group` suffix as artifactId to avoid collisions; but then we have different artifactId and feature id, so we diverge from upstream Maven models which are built for/by Tycho with artifactId==featureId
For the javadoc, we can just put the source artifact pretending it's javadoc.

**Comment by pzi-dsa** [comment]
> I don't really see published features actually being significantly useful for anyone such that it would justify the significant additional effort involved in publishing these things.

The major use case is pretty much what @laeubi described. I.e. adding features as dependencies to a (Maven) project in order to automatically add all referenced artifacts to the classpath.

> Would you be willing to participate to the development effort?

I'm afraid the priority of this has also decreased on our side, as we will probably stick to p2 repositories for the foreseeable future, meaning I most likely won't have much time to further invest into this topic. :(

That being said, since this looks like more than just a trivial change, I think it makes the most sense to close this issue for now, as neither side will be able to work on it anytime soon. However, I thank all of you for your responses, as well as the suggestions and if this issue comes up again, I at least know where I have to start looking!
