### ISSUE TITLE
Deploy Maven SNAPSHOT artifacts

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.releng#58]
Currently p2->Maven translation and deployment only happens for releases. In order to facilitate testing and verification and early adoption, we should publish frequent snapshots.
Snapshots would probably have to land to repo.eclipse.org since I believe OSSRH doesn't allow snapshots.

**Comment by HannesWell** [comment]
That would be very useful for downstream users, like Tycho and others (I think there will be more once this is available).
Ideally snapshots for Maven are published on each I-build, just like they produce a corresponding I-build repo.

> Snapshots would probably have to land to repo.eclipse.org since I believe OSSRH doesn't allow snapshots.

OSSRH has a special repo dedicated to snapshots (not sure if this is also used for new projects, because the deployment repo changed recently and maybe the corresponding snapshot repo changed too):
https://oss.sonatype.org/content/repositories/snapshots

IIRC if a projects deploys its snapshots to that repo they are automatically available if one uses a snapshot version, without the need to add a extra repo.

A standard distribution management section could then looks like this:
```
<distributionManagement>
	<repository>
		<id>ossrh</id>
		<url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
	</repository>
	<snapshotRepository>
		<id>ossrh</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	</snapshotRepository>
</distributionManagement>
```

**Comment by mickaelistria** [comment]
Done with #59 and some instructions to deploy snapshots are available at https://www.eclipse.org/lists/platform-releng-dev/msg38567.html
